name: CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build: 
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    # Docker 이미지 Build       
    - name: docker image build
      run:
        docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_BUILD_FILE }} .
    
    # DockerHub Login
    - name: docker login 
      uses: docker/login-action@v2
      with: 
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

    # Docker Hub push
    - name: docker Hub push
      run: docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_BUILD_FILE }}
        
  # 배포
  deploy:
    needs: build # build 후에 실행되도록 정의
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # ec2 접속 및 deploy.sh 실행
      - name: Application Run
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_REMOTE_IP }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            sudo su
            cd ../project
            sudo sh deploy.sh


            
